[phases.setup]
nixPkgs = [
  "php",
  "php82Extensions.pdo",
  "php82Extensions.pgsql",
  "php82Extensions.mbstring",
  "php82Extensions.bcmath",
  "composer"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "ls -la && ls public && php -S 0.0.0.0:$PORT -t public"